### ISSUE TITLE
Build fails on the armv7 architecture: undefined reference to NCBI_SwapPointers

### ISSUE THREAD

**Issue by yurivict** [ncbi/ncbi-cxx-toolkit-public#8]
```
ld: error: /wrkdirs/usr/ports/biology/ncbi-cxx-toolkit/work/ncbi-cxx-toolkit-public-release-28.0.0/Clang1405-ReleaseMTDLL/lib/libconnect.so: undefined reference to NCBI_SwapPointers [--no-allow-shlib-undefined]
```

[log](https://pkg-status.freebsd.org/ampere3/data/132releng-armv7-default/8633b2706862/logs/ncbi-cxx-toolkit-28.0.0.log)

```src/corelib/ncbiatomic.cpp``` has ```NCBI_SwapPointers``` implementation conditional on ```NCBI_SLOW_ATOMIC_SWAP``` which is likely not defined on armv7 leaving this symbol undefined.

Version: 28.0.0
FreeBSD 13.2

**Comment by vakatov** [comment]
@ucko - can you please take a look? You were the last to person to work with NCBI_SwapPointers()... which was 15 years ago ;-)

**Comment by ucko** [comment]
(Pasting an emailed comment that I sent a few hours ago but never showed up and taking the opportunity to add a bit of formatting; if it eventually does show up, I apologize in advance for the resulting duplication.)

I’ve committed a pair of adjustments to the traditional Autotools-based build system (which you appear to be using) that should help.  These fixes are so far in place only in-house, but should automatically propagate to GitHub by tomorrow.

FTR, my review of the relevant logic indicates that `NCBI_SLOW_ATOMIC_SWAP` was getting set correctly; I’m pretty sure you would have otherwise encountered errors from the compiler rather than the linker.  However, build-system logic meant to reflect the header logic incorrectly lumped 32-bit ARM with 64-bit ARM, for which the Toolkit instead arranges to use inline assembly.  (NB: The CMake build system does not so far account for any `NCBI_SLOW_ATOMIC_SWAP` platforms.)

Thanks for the report, and sorry you ran into trouble!

**Comment by yurivict** [comment]
Thank you, @ucko .

I will try it once the next release will be out.

Yuri

**Comment by vakatov** [comment]
Fixed in code, so - resolving.
